version: "3.3"

services:
  gbans:
    build:
      context: "."
      dockerfile: Dockerfile
    volumes:
      - ./config.yml:/app/config.yml
    depends_on:
      - postgres
    environment:
      BDAPI_DATABASE_DSN: postgresql://bdapi:bdapi@postgres:5445/bdapi
    networks:
      - bdapi_dev_network
    command: ./bd-api serve
  postgres:
    image: postgres:15-bullseye
    restart: always
    ports:
      - "127.0.0.1:5445:5432"
    environment:
      POSTGRES_USER: bdapi
      POSTGRES_DB: bdapi
      POSTGRES_PASSWORD: bdapi
    networks:
      - bdapi_dev_network

networks:
  bdapi_dev_network: