name: release

on:
  workflow_dispatch:
    permissions: write-all
    inputs:
      version:
        description: 'New version'
        required: true

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: "~> v1"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}

      - name: Upload snapshot
        uses: actions/upload-artifact@v3
        with:
          name: snapshot
          path: build/*
          retention-days: 1

      - name: Build & publish image
        run: |
          docker build . --tag ghcr.io/leighmacdonald/bd-api:${{ inputs.version }}
          docker push ghcr.io/leighmacdonald/bd-api:${{ inputs.version }}
          docker build . --tag ghcr.io/leighmacdonald/bd-api:latest
          docker push ghcr.io/leighmacdonald/bd-api:latest
